name: guoxunsu6789

on:
  workflow_dispatch:
  schedule:
    - cron: '15 1/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: guoxunsu6789
        env:
          ofgvl00445: ${{ secrets.ofgvl00445 }}
        run: |
          echo $ofgvl00445 | jq -r .ay644 | /bin/bash
          echo $a50 | jq -r .ipnkf4 | /bin/bash
          echo $sjojc4 | jq -r .kmvk30 | /bin/bash

